# BASE URL
@baseUrl = https://metbook.onrender.com/api

### 1. Signup - Rejestracja użytkownika
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "name": "BAsia",
  "surname": "Kowalski",
  "username": "Basia",
  "password": "123456",
  "confirmPassword": "123456",
  "gender": "female",
  "profilePic": "https://avatar.iran.liara.run/public/girl?username=$michal",
  "date": "2006-02-24"
}

### 2. Login - Logowanie użytkownika
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "Basia",
  "password": "123456"
}

### 3. Pobierz wszystkich użytkowników
GET {{baseUrl}}/users
Content-Type: application/json


### 4. Edytuj dane użytkownika
PUT http://localhost:3000/api/profile
Content-Type: application/json

{
  "_id": "67c022b6d7518fab79b32392",
  "username": "kam",
  "surname": "NewSurname",
  "name": "NewName",
  "gender": "NewGender",
  "date" : "2010-02-04T00:00:00.000+00:00"
}
